export const API_URL = {
  SIGN_UP: '/auth/signup',
  LOGIN: '/auth/login',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  FORMS: '/forms',
  FOLDERS: '/folders',
  INDEPENDENT_FOLDER: '/folders/independent',
  TEAMS: '/teams',
  USER_PROFILE: '/users/my-profile',
  CHANGE_PASSWORD: '/users/change-password',
  UPLOAD_IMAGE: '/images/upload',
  UPLOAD_FILE: '/files/upload',
  ADD_TO_FOLDER: '/:formId/folder/:folderId/add',
  RESPONSES: 'responses',
};
